version: "3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    build: .
    # command: python3 manage.py runserver
    command: make run-dev
    restart: on-failure
    ports:
      - 8000:8000
    # links:
    #   - db
    depends_on:
      - db
