# Generated by Django 4.1.7 on 2023-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("buy_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("sell_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("description", models.CharField(max_length=256)),
            ],
        ),
    ]
